const burkinaCities = [
  { key: "ouagadougou", value: "Ouagadougou" },
  { key: "bobo_dioulasso", value: "Bobo-Dioulasso" },
  { key: "banfora", value: "Banfora" },
  { key: "dedougou", value: "Dédougou" },
  { key: "diapaga", value: "Diapaga" },
  { key: "dori", value: "Dori" },
  { key: "fada_ngourma", value: "Fada N’Gourma" },
  { key: "gaoua", value: "Gaoua" },
  { key: "gorom_gorom", value: "Gorom-Gorom" },
  { key: "houndsé", value: "Houndé" },
  { key: "kaya", value: "Kaya" },
  { key: "koudougou", value: "Koudougou" },
  { key: "kongoussi", value: "Kongoussi" },
  { key: "leo", value: "Léo" },
  { key: "manga", value: "Manga" },
  { key: "nouna", value: "Nouna" },
  { key: "ouahigouya", value: "Ouahigouya" },
  { key: "po", value: "Pô" },
  { key: "reomargo", value: "Réo" },
  { key: "tenkodogo", value: "Tenkodogo" },
  { key: "ziniare", value: "Ziniaré" },
  { key: "yako", value: "Yako" },
  { key: "djibo", value: "Djibo" },
  { key: "bogande", value: "Bogandé" },
  { key: "sapouy", value: "Sapouy" },
  { key: "diebo", value: "Diébougou" },
  { key: "koupela", value: "Koupéla" },
  { key: "titao", value: "Titao" },
  { key: "zabre", value: "Zabré" },
  { key: "solenzo", value: "Solenzo" },
  { key: "korsimoro", value: "Korsimoro" },
  { key: "pama", value: "Pama" },
  { key: "bousse", value: "Boussé" },
  { key: "arbinda", value: "Arbinda" },
  { key: "garango", value: "Garango" },
  { key: "bittou", value: "Bittou" },
  { key: "zongo", value: "Zongo" },
  { key: "oahigouya", value: "Ouahigouya" },
  { key: "kantchari", value: "Kantchari" },
  { key: "sebba", value: "Sebba" },
  { key: "zondoma", value: "Zondoma" },
  { key: "tougan", value: "Tougan" },
  { key: "pouytenga", value: "Pouytenga" },
  { key: "kombissiri", value: "Kombissiri" },
  { key: "koupela", value: "Koupéla" }
];

export default burkinaCities;
